#include "token.h"
#include <stdio.h>
#include <string.h>

static const char* token_names[] = {
    [TOKEN_LEFT_PAREN] = "LEFT_PAREN",
    [TOKEN_RIGHT_PAREN] = "RIGHT_PAREN",
    [TOKEN_LEFT_BRACE] = "LEFT_BRACE",
    [TOKEN_RIGHT_BRACE] = "RIGHT_BRACE",
    [TOKEN_LEFT_BRACKET] = "LEFT_BRACKET",
    [TOKEN_RIGHT_BRACKET] = "RIGHT_BRACKET",
    [TOKEN_COMMA] = "COMMA",
    [TOKEN_DOT] = "DOT",
    [TOKEN_SEMICOLON] = "SEMICOLON",
    [TOKEN_PLUS] = "PLUS",
    [TOKEN_MINUS] = "MINUS",
    [TOKEN_STAR] = "STAR",
    [TOKEN_SLASH] = "SLASH",
    [TOKEN_PERCENT] = "PERCENT",
    [TOKEN_COLON] = "COLON",

    [TOKEN_BANG] = "BANG",
    [TOKEN_BANG_EQUAL] = "BANG_EQUAL",
    [TOKEN_EQUAL] = "EQUAL",
    [TOKEN_EQUAL_EQUAL] = "EQUAL_EQUAL",
    [TOKEN_GREATER] = "GREATER",
    [TOKEN_GREATER_EQUAL] = "GREATER_EQUAL",
    [TOKEN_LESS] = "LESS",
    [TOKEN_LESS_EQUAL] = "LESS_EQUAL",
    [TOKEN_ARROW] = "ARROW",
    [TOKEN_PLUS_EQUAL] = "PLUS_EQUAL",
    [TOKEN_MINUS_EQUAL] = "MINUS_EQUAL",
    [TOKEN_STAR_EQUAL] = "STAR_EQUAL",
    [TOKEN_SLASH_EQUAL] = "SLASH_EQUAL",
    [TOKEN_PLUS_PLUS] = "PLUS_PLUS",
    [TOKEN_MINUS_MINUS] = "MINUS_MINUS",

    [TOKEN_IDENTIFIER] = "IDENTIFIER",
    [TOKEN_STRING] = "STRING",
    [TOKEN_NUMBER] = "NUMBER",

    [TOKEN_AND] = "AND",
    [TOKEN_ELSE] = "ELSE",
    [TOKEN_FALSE